# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prispevky', '0002_auto_20180702_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='prispevky',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
